[default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"  # Default Solidity version
optimizer = true
optimizer_runs = 1000
via-ir = true
[profile.default]
src = "src"
out = "out"
solc_version = "0.8.20"
libs = ["lib"]

[profile.solidity]
versions = ["0.8.20", "0.6.12"]
libs = ["lib"]

[profile.test]
src = "test"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@pythnetwork/=node_modules/@pythnetwork/",
    "@uniswap/v3-periphery/=node_modules/@uniswap/v3-periphery/",
    "@uniswap/v3-core/=node_modules/@uniswap/v3-core/",
    "@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/",
    "solady/=node_modules/solady/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@ds-test/=lib/forge-std/lib/ds-test/src/",
    "@forge-std/=lib/forge-std/src/",
    "./=src/",
    "@pythnetwork/=node_modules/@pythnetwork/",
    "@uniswap/=node_modules/@uniswap/",
    "test/mocks/=src/test/mocks/"
]

libraries = [
    "src/helpers/AssetHelper.sol:AssetHelper:${ASSET_HELPER_ADDRESS}",
    "src/helpers/OfferHelper.sol:OfferHelper:${OFFER_HELPER_ADDRESS}",
    "src/helpers/DotcOfferHelper.sol:DotcOfferHelper:${DOTC_OFFER_HELPER_ADDRESS}"
]